#!/bin/sh

export XAUTHORITY=/home/basti/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"
# Pass 1 as an argument for charging, 0 for discharging
BATTERY_CHARGING=$1
BATTERY_LEVEL=`acpi -b | grep "Battery 0" | grep -P -o '[0-9]+(?=%)'`
BATTERY_REMAINING=`acpi -b | awk '{print $5}'`

# Send notifications
if [ $BATTERY_CHARGING -eq 1 ]; then
    notify-send "Charging" "${BATTERY_LEVEL}% of battery charged." -u low -i $(~/.config/polybar/scripts/battery_notif.sh get_charging_icon) -t 3000 -r 9991
elif [ $BATTERY_CHARGING -eq 0 ]; then
    notify-send "Discharging" "${BATTERY_LEVEL}% of battery remaining." -u low -i $(~/.config/polybar/scripts/battery_notif.sh get_icon) -t 3000 -r 9991
fi
